language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: jexmppiDklexpnbi2YCU9w6H+BI1yvew0kndqEU66PSi51/MFX85kuwGL86317F3TkZC94C3tZnvNw7Hig47ft7zISQBBnFBkWQ6BIFxvxV2rVitl173v2O/fteHnzi5Y8gU0R40MBkAfx0PYqXqBQfby4ofWyvoYFzcdJ2vk7IxC9ULkC0nMREnIdwdgk0m2zYNz8beuoSPnfLclfRASP34LttelEP9PVPsZwYfmWbZDgHpJHVi5VJUFH18CeoG29lWv4UNc4M/FXCJEMHjFTayUced0uE8YGQkfjm4sHqkEp3juyj7ZfpJFD1jngMqbtFKXWBedTtaXblJWgWNulhew0IniYvbupU8xPK2pGxqOZNxd6fn3Hv5nnJc0aWziA8JN11eMKYsyHh+5LPbhYjBof9BM8FWSgLCUVBgN5py9Uu/qZhtkjMe7ZRTvFR0qsylgtbkgOPReY1Yh9Tok9YjKc0I6eALB9578aY+BPTaFYXml94RQhHb6sRSOjMHIMWUQt0g6vk3YGV5YNI50SWssmyJlVF2rcqLhBxizQ8matCNqs5vy3oXsErvWUgIdCiHYn+TJLjSo88pafIIf1dlDMGY/OnhXXkHpHFZEizSj8ZVxsdcJVKsy4TBMltM0IPlinUtzwqoMvUcwNAjziu8j7c/fqmk7rk0hjdQniY=
  app: blog-app-mongoose-challenge-solution
  on:
    repo: Kendallyn/blog-app-mongoose-challenge-solution
